"""create table projects

Revision ID: 047cb6f54e24
Revises: 
Create Date: 2024-07-29 18:08:14.683363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047cb6f54e24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador projeto.'),
    sa.Column('project_name', sa.String(), nullable=False, comment='Nome do projeto.'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='Data de início do projeto.'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='Data de término do projeto.'),
    sa.Column('initial_budget', sa.Float(), nullable=False, comment='Orçamento inicial do projeto.'),
    sa.Column('project_cost', sa.Float(), nullable=False, comment='Custo total do projeto.'),
    sa.Column('revenue', sa.Float(), nullable=False, comment='Receita do projeto.'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Projects')
    # ### end Alembic commands ###
